# Build stage
FROM node:18 AS build
WORKDIR /app

COPY .env .env
COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# Production stage with NGINX
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html/marketplace
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
