# Build stage
FROM node:18 AS build
WORKDIR /app

# Set environment variable for API URL using Docker service name
ENV VITE_API_URL=/marketplace/api

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# Production stage with NGINX
FROM nginx:alpine
# Install curl for healthcheck
RUN apk add --no-cache curl

COPY --from=build /app/dist /usr/share/nginx/html/marketplace
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
