version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3001:3001"
    environment:
      - HOST=0.0.0.0
      - PORT=3001
      - BASE_URL=http://147.93.27.172:3001
      - ADMIN_EMAIL=admin@gmail.com
      - ADMIN_PASSWORD=admin@123
      - DATABASE_URL=postgresql://user:password@db:5432/veloce?schema=public
    depends_on:
      - db
    networks:
      - veloce-net

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    networks:
      - veloce-net

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=veloce
      - TZ=Asia/Kolkata
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - veloce-net

volumes:
  db_data:

networks:
  veloce-net:
    driver: bridge
