services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3001:3001"
    environment:
      - HOST=localhost
      - PORT=3001
      - DATABASE_URL= prisma+postgres://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqd3RfaWQiOjEsInNlY3VyZV9rZXkiOiJza19xVDZoNmx6RHZwYlYzRlJydUhGN3YiLCJhcGlfa2V5IjoiMDFLMEdWOUZBRDhZWjQ2QkszMTNLUU1TQTciLCJ0ZW5hbnRfaWQiOiJiZDA5ZmE1N2Y4OTE1NjJlYmQ4OTNiM2ZhZjVmODMyZDg0N2YzOTZlMmYzOWU2MDA4NDA1NDlhNWI2MDk5Mzc4IiwiaW50ZXJuYWxfc2VjcmV0IjoiZTFjOGI3YzItMmE0MC00MDE4LWJkMTctOWZmMWFjNzA2NDc2In0._RvKhIoIkU9ylcU6yShnSO5spHbgGyTTwVsReL-aiw8
    depends_on:
      - db
    volumes:
      - ./backend:/app
    networks:
      - veloce-net

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://backend:3001
    networks:
      - veloce-net

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: veloce
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - veloce-net

volumes:
  db_data:

networks:
  veloce-net:
    driver: bridge